#!/bin/sh
# Copyright (C) 2010-2018 Greenbone AG
# Copyright (C) 2026 Suricatoos
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.

# Report generator script: Suricatoos Premium PDF.
#
# This report generator initially creates a LaTeX file using a XML
# transformation with the tool xsltproc. In a second step the LaTeX file is
# processed with the tool pdflatex which results in the final PDF file. The
# branded logo PDFs that ship in this report format bundle are referenced by
# the stylesheet via \includegraphics and are resolved relative to this
# directory, which is the working directory while the generator runs.
# The intermediate files are stored under a temporary directory.

TMP=`mktemp -d` || exit 1

# Make the bundled logo assets available next to the intermediate .tex file so
# that pdflatex (which runs with -output-directory ${TMP}) can find them.
cp ./suricatoos-*.pdf "${TMP}/" 2>/dev/null

xsltproc ./latex.xsl $1 > ${TMP}/report.tex 2>/tmp/err.out

pdflatex -interaction batchmode -output-directory ${TMP} ${TMP}/report.tex > /dev/null 2>&1

# Run a second time to resolve references, the table of contents and the
# "page X of Y" page numbering assembled during the first run.
pdflatex -interaction batchmode -output-directory ${TMP} ${TMP}/report.tex > /dev/null 2>&1 &

wait

cat ${TMP}/report.pdf && rm -rf ${TMP}
