services:
  gsa:
    image: suricatoos/gsa:stable
    environment:
      GSA_VENDOR_TITLE: "Suricatoos"
      GSA_VENDOR_VERSION: "Suricatoos 1.0"
  gsad:
    image: suricatoos/gsad:stable
  nginx:
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
