[suricatoos-login]
enabled  = true
filter   = suricatoos-login
logpath  = /var/log/suricatoos-nginx/login.log
maxretry = 8
findtime = 600
bantime  = 3600
action   = route
ignoreip = 127.0.0.1/8 ::1 172.16.0.0/12 <SEU_IP_ADMIN>
